### ISSUE TITLE
Diagonal elements of heat flux matrix when calculating mode diffusivity

### ISSUE THREAD

**Issue by uucai** [eminamitani/thermal_conductivity_code#7]
Hi,

The diagonal elements of heat fulx matrix seem to be included in this code, when calculating mode diffusivity Di. However, only off-diagonal elements of heat flux matrix are included in Allen-Feldman theory. So, Is this implemention correct? 

Zhuangli Cai

**Comment by eminamitani** [comment]
Hi,

Would you let me know some references about the diagonal element in Allen-Feldman theory? I followed the equations in the original paper by P. Allen and J. Feldman, Phys. Rev. B, 48, 12581. As far as I understand, Eq. B2 in that originates from the expansion of correlation function <SS> --><n|S|m><m|S|n>, thus, no obvious restriction on |m><m|.

**Comment by uucai** [comment]
Hi,

The diagonal element is **Eq. 25** in the paper, Phys. Rev. B, 1993, 48, 12581.  I think **Eq. 21** and **Eq. 22** are the thermal conductivity formula of Allen-Feldman theory. Maybe, including the diagonal element dosen't change the result, because the group velocity vii will be equal to zero and thus Sii is equal to zero for disorder materials.

**Comment by eminamitani** [comment]
I evaluate total thermal conductivity (off-diagonal + diagonal) in my code. As you suggested, Sii=0 for disordered material, so as far as this code is applied to disordered systems, the effect of the diagonal term would be negligible. 
I will try to make a version without the contribution of diagonal terms. Thank you for your suggestion.

**Comment by eminamitani** [comment]
I added an option to fix the diagonal matrix element of Sij. I confirmed that in aSi 512 atoms sample, this modification did not change the obtained results.

You can use this option by setting `fix_diag` tag in setup.yaml
```
    #fix diagonal element
    if(fix_diag):
        for i in range(nmodes):
            Sijx[i,i]=0.0
            Sijy[i,i]=0.0
            Sijz[i,i]=0.0
    
```
