### ISSUE TITLE
About  amorphous polyphenylene calculation

### ISSUE THREAD

**Issue by huangxiang701** [eminamitani/thermal_conductivity_code#8]
Dear Prof. Minamitani,
 Currently, I am calculating the thermal conductivity of amorphous polyphenylene using the pyAF software you developed. I have prepared the structure file and performed the calculation with reference to the case you provided. The difference with the case you provided is that my Lammps file is in real units, so I have post-processed the output dynamic matrix (i.e. multiplied by 0.042 to convert Kcal/mol to eV  in energy unit). However, I got an unusually high thermal conductivity result (above 9000 W/mK). I would appreciate any guidance you can give me.  Thank you for your time.

Xiang Huang
25 October 2023

**Comment by huangxiang701** [comment]
Thank you,Prof. Minamitani. I've sorted this problem.

**Comment by eminamitani** [comment]
Thank you for your information. Could you let me know how you solved the issue?  (another user may faced the same problem)

**Comment by huangxiang701** [comment]
Mostly following your provided case. I just tightened the convergence criterion for structural relaxation and turned off the "symmetrize_fc" option. Thank you.

**Comment by eminamitani** [comment]
Thank you so much for your information!
